version: '3.4'

services:
  calappoint.api:
    image: ${DOCKER_REGISTRY-}calappointapi
    build:
      context: .
      dockerfile: src/Calappoint.API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081" 

  calappoint.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "Calappoint.Database"
    environment:
      SA_PASSWORD: "calapoint@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./src/TRunner.Database/Database:/var/opt/mssql/data
    restart: always

  calappoint.seq:
    image: datalust/seq:latest
    container_name: "Calappoint.Seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    restart: always
  
  calappoint.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: "Calappoint.Identity"
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers.identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
  