version: '3.4'

services:
  calappoint.api:
    image: ${DOCKER_REGISTRY-}calappointapi
    build:
      context: .
      dockerfile: src\Calappoint.API\Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081" 

  calappoint.database:
       image: mcr.microsoft.com/mssql/server:2022-latest
       container_name: "Calappoint.Database"
       environment:
         SA_PASSWORD: "calapoint@123"
         ACCEPT_EULA: "Y"
       ports:
         - "1433:1433"
       volumes:
         - ./src/TRunner.Database/Database:/var/opt/mssql/data
       restart: always
  